#!/bin/bash

mkdir -p slurm_log
mkdir -p log
mkdir -p runs
mkdir -p ckpt

echo "saving old argument file to history"
cat args.txt >> .args.hist

python -c "from lib.cmd_utils import create_dataset_before; create_dataset_before('args.txt')"

rm -f args_cpu.txt
rm -f args_gpu.txt
python -c "from lib.cmd_utils import assign_cluster; assign_cluster('args.txt')"

echo "generating seeded args"
python -c "from lib.cmd_utils import seedify; seedify('args_gpu.txt')" $1 $2
python -c "from lib.cmd_utils import seedify; seedify('args_cpu.txt')" $1 $2

clear
cat args_gpu.txt
echo
read -p "Are you sure you want to run these arguments on gpu? (y/Y to proceed) " -n 1 -r
echo
if [[ $REPLY =~ ^[yY]$ ]]
then
        sbatch --array=1-$(wc -l args_gpu_seeded.txt | awk '{ print $1 }') slurm_script_gpu.sbatch
fi
clear
cat args_cpu.txt
echo
read -p "Are you sure you want to run these arguments on cpu? (y/Y to proceed) " -n 1 -r
echo
if [[ $REPLY =~ ^[yY]$ ]]
then
        sbatch --array=1-$(wc -l args_cpu_seeded.txt | awk '{ print $1 }') slurm_script_cpu.sbatch
fi
